from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest

from sensegnat.ingestion.csv_adapter import CsvEventAdapter


def _write_csv(tmp_path: Path, content: str) -> Path:
    p = tmp_path / "events.csv"
    p.write_text(content)
    return p


class TestCsvEventAdapter:
    def test_loads_all_rows(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "event_id,seen_at,source_host,source_user,destination,destination_port,protocol\n"
            "e1,2024-01-15T10:00:00,host-1,alice,203.0.113.10,443,tcp\n"
            "e2,2024-01-15T10:01:00,host-2,bob,10.0.0.1,22,tcp\n"
        ))
        events = list(CsvEventAdapter(p).fetch_events())
        assert len(events) == 2

    def test_iso_datetime_parsed(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "event_id,seen_at,source_host,destination,destination_port,protocol\n"
            "e1,2024-06-01T12:30:00,host-1,10.0.0.1,443,tcp\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.seen_at.year == 2024
        assert event.seen_at.month == 6
        assert event.seen_at.hour == 12
        assert event.seen_at.tzinfo == timezone.utc

    def test_epoch_float_timestamp_parsed(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "event_id,seen_at,source_host,destination,destination_port,protocol\n"
            "e1,1704067200.0,host-1,10.0.0.1,443,tcp\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.seen_at == datetime.fromtimestamp(1704067200.0, tz=timezone.utc)

    def test_fields_mapped_correctly(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "event_id,seen_at,source_host,source_user,destination,destination_port,protocol,bytes_out,bytes_in\n"
            "evt-42,2024-01-15T08:00:00,host-9,carol,198.51.100.5,8443,tcp,1024,512\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.event_id == "evt-42"
        assert event.source_host == "host-9"
        assert event.source_user == "carol"
        assert event.destination == "198.51.100.5"
        assert event.destination_port == 8443
        assert event.protocol == "tcp"
        assert event.bytes_out == 1024
        assert event.bytes_in == 512

    def test_protocol_lowercased(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "seen_at,source_host,destination,destination_port,protocol\n"
            "2024-01-15T10:00:00,host-1,10.0.0.1,53,UDP\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.protocol == "udp"

    def test_empty_source_user_becomes_none(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "seen_at,source_host,source_user,destination,destination_port,protocol\n"
            "2024-01-15T10:00:00,host-1,,10.0.0.1,443,tcp\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.source_user is None

    def test_missing_source_user_column_becomes_none(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "seen_at,source_host,destination,destination_port,protocol\n"
            "2024-01-15T10:00:00,host-1,10.0.0.1,443,tcp\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.source_user is None

    def test_missing_event_id_is_autogenerated(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "seen_at,source_host,destination,destination_port,protocol\n"
            "2024-01-15T10:00:00,host-1,10.0.0.1,443,tcp\n"
            "2024-01-15T10:01:00,host-1,10.0.0.2,443,tcp\n"
        ))
        events = list(CsvEventAdapter(p).fetch_events())
        assert events[0].event_id != ""
        assert events[0].event_id != events[1].event_id  # unique per row

    def test_missing_bytes_default_to_zero(self, tmp_path: Path) -> None:
        p = _write_csv(tmp_path, (
            "seen_at,source_host,destination,destination_port,protocol\n"
            "2024-01-15T10:00:00,host-1,10.0.0.1,443,tcp\n"
        ))
        event = list(CsvEventAdapter(p).fetch_events())[0]
        assert event.bytes_out == 0
        assert event.bytes_in == 0

    def test_sample_events_csv_loads(self) -> None:
        sample = Path(__file__).parent.parent / "examples" / "sample_events.csv"
        events = list(CsvEventAdapter(sample).fetch_events())
        assert len(events) == 6
        assert events[0].source_user == "alice"
        assert events[5].source_user is None  # last row has no user
